# Generated by Django 5.2.7 on 2025-10-03 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phone_generator", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneGenerationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_code", models.CharField(max_length=5)),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Number of phone numbers to generate"
                    ),
                ),
                (
                    "carrier_filter",
                    models.CharField(
                        blank=True,
                        help_text="Optional carrier filter",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "type_filter",
                    models.CharField(
                        blank=True,
                        help_text="Optional type filter (mobile/landline)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True, help_text="Current processing step", max_length=200
                    ),
                ),
                ("total_items", models.IntegerField(default=0)),
                ("processed_items", models.IntegerField(default=0)),
                ("successful_items", models.IntegerField(default=0)),
                ("failed_items", models.IntegerField(default=0)),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Task result and metadata"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if task failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_completion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="area_code",
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="validation_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="validation_source",
            field=models.CharField(
                default="internal",
                help_text="Source of validation (internal/external)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="carrier",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="prefix",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="type",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="phonenumber",
            index=models.Index(
                fields=["carrier", "type"], name="phone_gener_carrier_88807e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonenumber",
            index=models.Index(
                fields=["area_code", "valid_number"],
                name="phone_gener_area_co_938fc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phonenumber",
            index=models.Index(
                fields=["user", "project"], name="phone_gener_user_id_881e0c_idx"
            ),
        ),
        migrations.AddField(
            model_name="phonegenerationtask",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_tasks",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="phonegenerationtask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_generation_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="phonegenerationtask",
            index=models.Index(
                fields=["user", "status"], name="phone_gener_user_id_e87817_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonegenerationtask",
            index=models.Index(
                fields=["celery_task_id"], name="phone_gener_celery__bb32f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonegenerationtask",
            index=models.Index(
                fields=["-created_at"], name="phone_gener_created_50a26e_idx"
            ),
        ),
    ]
