# Generated by Django 5.2.7 on 2025-10-04 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phone_generator", "0002_add_performance_indexes"),
        ("phone_generator", "0002_phonegenerationtask_phonenumber_area_code_and_more"),
    ]

    operations = []
