# Generated by Django 5.2.7 on 2025-10-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_generator', '0003_merge_20251004_2015'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='phonegenerationtask',
            name='task_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='phonegenerationtask',
            name='task_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='phonenumber',
            name='phone_user_proj_arch_idx',
        ),
        migrations.RemoveIndex(
            model_name='phonenumber',
            name='phone_valid_type_carr_idx',
        ),
        migrations.RemoveIndex(
            model_name='phonenumber',
            name='phone_created_desc_idx',
        ),
    ]
