# Generated by Django 5.2.7 on 2025-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhonePrefix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=6, unique=True)),
                ("carrier", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("line_type", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["prefix"],
            },
        ),
        migrations.CreateModel(
            name="Proxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=15)),
                ("port", models.IntegerField()),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("ssl", models.BooleanField(default=False)),
                ("anonymity", models.CharField(blank=True, max_length=20, null=True)),
                ("valid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
