# Generated by Django 5.2.7 on 2025-10-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smtps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smtpmanager",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="smtpmanager",
            name="failed_emails",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="smtpmanager",
            name="health_check_failures",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="smtpmanager",
            name="is_healthy",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="smtpmanager",
            name="last_health_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="smtpmanager",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="smtpmanager",
            name="successful_emails",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="smtpmanager",
            name="tls",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="smtpmanager",
            name="total_emails_sent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="smtpmanager",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
