# Generated by Django 4.2.7 on 2025-10-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smtps", "0002_alter_smtpmanager_options_smtpmanager_failed_emails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtpmanager",
            name="average_response_time",
            field=models.FloatField(
                blank=True, help_text="Average response time in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="smtpmanager",
            name="consecutive_failures",
            field=models.IntegerField(
                default=0, help_text="Consecutive failures since last success"
            ),
        ),
        migrations.AddField(
            model_name="smtpmanager",
            name="last_error_message",
            field=models.TextField(
                blank=True, help_text="Last error message", null=True
            ),
        ),
        migrations.AddField(
            model_name="smtpmanager",
            name="last_response_time",
            field=models.FloatField(
                blank=True, help_text="Last response time in seconds", null=True
            ),
        ),
    ]
