# Generated by Django 5.2.7 on 2025-10-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskprogress",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
