# Generated by Django 5.2.7 on 2025-10-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_tasknotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskprogress",
            name="category",
            field=models.CharField(
                choices=[
                    ("phone_generation", "Phone Generation"),
                    ("phone_validation", "Phone Validation"),
                    ("sms_sending", "SMS Sending"),
                    ("data_export", "Data Export"),
                    ("data_import", "Data Import"),
                    ("general", "General"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
