# Generated by Django 5.2.7 on 2025-10-03 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms_sender", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Campaign name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Campaign description"),
                ),
                (
                    "message_template",
                    models.TextField(help_text="Message template with macro support"),
                ),
                (
                    "target_carrier",
                    models.CharField(
                        blank=True,
                        help_text="Target specific carrier",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        help_text="Target type (mobile/landline)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "target_area_codes",
                    models.JSONField(
                        blank=True, default=list, help_text="List of target area codes"
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, help_text="When to send the campaign", null=True
                    ),
                ),
                ("send_immediately", models.BooleanField(default=False)),
                (
                    "batch_size",
                    models.IntegerField(
                        default=100, help_text="Number of messages per batch"
                    ),
                ),
                (
                    "rate_limit",
                    models.IntegerField(default=10, help_text="Messages per minute"),
                ),
                ("use_proxy_rotation", models.BooleanField(default=True)),
                ("use_smtp_rotation", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                ("total_recipients", models.IntegerField(default=0)),
                ("messages_sent", models.IntegerField(default=0)),
                ("messages_delivered", models.IntegerField(default=0)),
                ("messages_failed", models.IntegerField(default=0)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "message_content",
                    models.TextField(
                        help_text="Rendered message content with macros replaced"
                    ),
                ),
                ("carrier", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "carrier_gateway",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "smtp_server",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("proxy_used", models.CharField(blank=True, max_length=200, null=True)),
                ("send_attempts", models.IntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="sms_sender.smscampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="smscampaign",
            index=models.Index(
                fields=["user", "status"], name="sms_sender__user_id_49bd2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smscampaign",
            index=models.Index(
                fields=["scheduled_time"], name="sms_sender__schedul_91500d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smscampaign",
            index=models.Index(
                fields=["-created_at"], name="sms_sender__created_2e037c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(
                fields=["campaign", "delivery_status"],
                name="sms_sender__campaig_8b4825_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(
                fields=["phone_number"], name="sms_sender__phone_n_f58c53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smsmessage",
            index=models.Index(
                fields=["delivery_status"], name="sms_sender__deliver_e00f53_idx"
            ),
        ),
    ]
