# Generated by Django 5.2.7 on 2025-10-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms_sender", "0002_smscampaign_smsmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smscampaign",
            name="custom_macros",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom macro values for this campaign",
            ),
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="recipient_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Recipient-specific data for macro replacement",
            ),
        ),
    ]
