# Generated by Django 5.2.7 on 2025-10-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_sender", "0006_abtestexperiment_abtestvariant_abtestresult_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigndeliverysettings",
            name="applied_template_id",
            field=models.CharField(
                blank=True,
                help_text="Identifier of the optimisation template applied to this campaign",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaigndeliverysettings",
            name="selected_proxy_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Explicit proxy server IDs to prioritise during delivery",
            ),
        ),
        migrations.AddField(
            model_name="campaigndeliverysettings",
            name="selected_smtp_account_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Explicit SMTP account IDs to prioritise during delivery",
            ),
        ),
    ]
