# Generated by Django 5.2.9 on 2025-12-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0007_campaigndeliverysettings_applied_template_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscampaign',
            name='email_subject',
            field=models.CharField(default='SMS', help_text='Subject line for email', max_length=200),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='sender_name',
            field=models.CharField(default='SMS', help_text='Sender name for email header', max_length=100),
        ),
    ]
