version: "3.8"

services:
  # Redis
  redis:
    image: redis:alpine
    container_name: god_bless_redis
    restart: always

  # Database Postgres
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=god_bless_postgres
      - POSTGRES_USER=god_bless_postgres
      - POSTGRES_PASSWORD=god_bless_postgres
    container_name: god_bless_postgres_db
    restart: always

  # Django Application
  god_bless_app:
    build:
      context: .
    volumes:
      - .:/god_bless_django
      - ./static_cdn:/var/lib/static_cdn
    ports:
      - 6161:6161
    container_name: god_bless_app
    command: daphne -b 0.0.0.0 -p 6161 god_bless_pro.asgi:application
    environment:
      - DOCKER_ENV=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=god_bless_postgres
      - POSTGRES_USER=god_bless_postgres
      - POSTGRES_PASSWORD=god_bless_postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CREATE_SUPERUSER=false
      - LOAD_INITIAL_DATA=false
    depends_on:
      - db
      - redis
    restart: always

  # React Application (New Platform)
  god_bless_platform:
    build:
      context: ../god_bless_platform
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173" # Vite dev server port
    volumes:
      - ../god_bless_platform:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:6161/api
      - VITE_WS_URL=ws://localhost:6161/ws/
      - VITE_APP_NAME=God Bless Platform
      - VITE_VERSION=1.0.0
      - VITE_ENVIRONMENT=development
    depends_on:
      - god_bless_app
    restart: always

  # Celery Worker
  celery:
    restart: always
    build:
      context: .
    command: celery -A god_bless_pro worker -l DEBUG
    volumes:
      - .:/god_bless_django
    container_name: god_bless_celery
    environment:
      - DOCKER_ENV=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=god_bless_postgres
      - POSTGRES_USER=god_bless_postgres
      - POSTGRES_PASSWORD=god_bless_postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CREATE_SUPERUSER=false
      - LOAD_INITIAL_DATA=false
    depends_on:
      - db
      - redis
      - god_bless_app

  # Celery Beat
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A god_bless_pro beat -l DEBUG
    volumes:
      - .:/god_bless_django
    container_name: god_bless_celery_beat
    environment:
      - DOCKER_ENV=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=god_bless_postgres
      - POSTGRES_USER=god_bless_postgres
      - POSTGRES_PASSWORD=god_bless_postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CREATE_SUPERUSER=false
      - LOAD_INITIAL_DATA=false
    depends_on:
      - db
      - redis
      - god_bless_app

volumes:
  static_cdn:
  postgres_data:
