# Generated by Django 5.2.7 on 2025-10-03 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_userapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_rate_limit",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("smtp_rotation_enabled", models.BooleanField(default=True)),
                ("proxy_rotation_enabled", models.BooleanField(default=True)),
                (
                    "delivery_delay_min",
                    models.IntegerField(
                        default=1, help_text="Minimum delay in seconds"
                    ),
                ),
                (
                    "delivery_delay_max",
                    models.IntegerField(
                        default=5, help_text="Maximum delay in seconds"
                    ),
                ),
                (
                    "delivery_delay_seed",
                    models.IntegerField(
                        blank=True,
                        help_text="Random seed for delay generation",
                        null=True,
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        default=100, help_text="Default batch size for bulk operations"
                    ),
                ),
                (
                    "sms_rate_limit_per_minute",
                    models.IntegerField(
                        default=10, help_text="SMS sending rate limit per minute"
                    ),
                ),
                (
                    "carrier_specific_rate_limits",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Carrier-specific rate limits",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
